import { Geist, Geist_Mono, Nabla } from "next/font/google";
import { GlobalMappingProvider } from "@/app/Components/Mapping/GlobalMappingProvider";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const nabla = Nabla({
  variable: "--font-nabla",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link
          href="https://fonts.googleapis.com/css2?family=Electrolize&display=swap"
          rel="stylesheet"
        />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Asimovian&display=swap"
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${nabla.variable} antialiased`}
      >
        <GlobalMappingProvider>{children}</GlobalMappingProvider>
      </body>
    </html>
  );
}
